import { formatBytes } from "../../../shared/format/bytes";
import type { HardwareSnapshot } from "../../../shared/ipc/compare/hardware";
import type { ModelVerdict, Readiness, ReadinessProfile } from "../../../shared/ipc/eval/readiness";

const STATUS_LABEL: Record<Readiness, string> = { ready: "READY", conditional: "CONDITIONAL", not_ready: "NOT READY" };

const NA = "N/A";
const pct = (n: number | null | undefined): string => (n == null ? NA : `${Math.round(n * 100)}%`);
const num = (n: number | null | undefined, digits = 2): string => (n == null ? NA : n.toFixed(digits));
/// Escape the GFM table cell delimiter so a model name with a pipe can't break
/// the column layout when pasted into a GitHub Issue / Reddit / Discord.
const cell = (s: string): string => s.replace(/\|/g, "\\|");

/// The hardware profile as a bolded list above the table — the explicit shared
/// context for a published verdict. Every field is guarded; an unmeasured one is
/// dropped, never emitted as `undefined` (see `no-fake-metrics`).
function hardwareLines(hw: HardwareSnapshot | null): string[] {
  if (!hw) return [];
  const lines = ["**Hardware**"];
  if (hw.cpu) lines.push(`- CPU: ${hw.cpu}`);
  lines.push(`- Memory: ${formatBytes(hw.total_memory_bytes)} total${hw.is_apple_silicon ? " (Apple Silicon, unified)" : ""}`);
  const gpu = hw.gpu;
  if (gpu?.name) lines.push(`- GPU: ${gpu.name}${gpu.vram_total_bytes ? ` (${formatBytes(gpu.vram_total_bytes)} VRAM)` : ""}`);
  if (hw.estimated_bandwidth_gbps) lines.push(`- Bandwidth: ${hw.estimated_bandwidth_gbps} GB/s`);
  return [...lines, ""];
}

const yn = (b: boolean): string => (b ? "yes" : "no");
function profileLine(p: ReadinessProfile): string {
  return (
    `**Profile gates (${cell(p.name)}):** Min Pass^k ${Math.round(p.min_pass_k * 100)}% · ` +
    `forbid loops ${yn(p.forbid_infinite_loop)} · forbid fake-done ${yn(p.forbid_hallucinated_completion)} · ` +
    `require full VRAM ${yn(p.require_full_vram)} · require native FC ${yn(p.require_native_fc)}`
  );
}

const tableRow = (m: ModelVerdict): string =>
  `| ${cell(m.model)} | ${cell(m.backend)} | ${STATUS_LABEL[m.verdict.status]} | ` +
  `${pct(m.pass_k)} | ${num(m.effort)} | ${num(m.avg_steps, 1)} |`;

/// The per-model diagnostic reasons block — mirrors the HTML export: blocking (✗)
/// then conditions (!), or "✓ Meets all criteria" when clean.
function reasonsBlock(m: ModelVerdict): string[] {
  const v = m.verdict;
  const path = v.path === "native_fc" ? "Native FC" : "Prompt-Based";
  const head = `### ${cell(m.model)} — ${STATUS_LABEL[v.status]} (${path})`;
  if (v.blocking.length === 0 && v.conditions.length === 0) return [head, "- ✓ Meets all criteria", ""];
  return [head, ...v.blocking.map((b) => `- ✗ ${b}`), ...v.conditions.map((c) => `- ! ${c}`), ""];
}

/// Build a shareable, offline GitHub-flavored Markdown readiness report. Pure
/// (no DOM, no network). Unmeasured metrics render "N/A", never fabricated.
export function buildReadinessMarkdown(
  verdicts: ModelVerdict[],
  profile: ReadinessProfile,
  collectionId: string,
  generatedAtIso: string,
  hardware: HardwareSnapshot | null = null,
): string {
  const out: string[] = [
    `# Local Agent Readiness — ${collectionId}`,
    "",
    `> Verdicts are measured against the **${profile.name}** profile, not objective truth.`,
    "",
    ...hardwareLines(hardware),
    profileLine(profile),
    "",
    "| Model | Backend | Readiness | Pass^k | Effort | Steps |",
    "|---|---|---|---|---|---|",
    ...(verdicts.length ? verdicts.map(tableRow) : ["| _No models assessed._ |  |  |  |  |  |"]),
    "",
    ...verdicts.flatMap(reasonsBlock),
    `_Generated by QuantaMind — https://quantamind.co · ${generatedAtIso}_`,
  ];
  return out.join("\n");
}
